name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      run: |
             export VERSION=$(grep -E '^Rev:\s' README.md | grep -oE '([0-9]+\.){2}[0-9]+')
             #docker build . --file Dockerfile --tag test-fastapi:$VERSION
             echo $ACCESS_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
    - name: Show the image
      run: docker images | grep test-fastapi || true