name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
             export VERSION=$(grep -E '^Rev:\s' README.md | grep -oE '([0-9]+\.){2}[0-9]+')
             docker build . --file Dockerfile --tag test-fastapi:$VERSION
    - name: Show the image
      run: docker images
